apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
spec:
  type: NodePort
  ports:
      - port: {{ .Values.driver.port }}
        targetPort: {{ .Values.driver.port }}
  selector:
      app: {{ .Release.Name }}
