compute:
    name: compute
    image:
        name: polusai/compute-api:0.0.4
        secret: null
    ingress:
        enabled: false
        host: null
    drivers:
        argo:
            url: http://argo-driver:7999
        slurm:
            url: http://slurm-driver:7998
    auth:
        url: null
    cors:
        origin: '*'

mongodb:
    name: WorkflowDb
    connectionString: connectionString
    port: 27017
    persistence:
        enabled: false
        size: 256Mi
        storageClass: aws-efs
    auth:
        ## @param auth.enabled Enable authentication
        ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
        ##
        enabled: false
