pipeline {
    agent {
        docker { 
            image 'sunnielyu/helm-jenkins:0.4.0'
            label 'linux && build && aws'
        }
    }
    options { timestamps () }
    parameters {
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'kube-eks-ci-compute', description: 'Kubernetes Cluster to deploy')
        string(name: 'KUBERNETES_NAMESPACE', defaultValue: 'default', description: 'Cluster Namespace to deploy')
        string(name: 'HELM_DEPLOYMENT_NAME', defaultValue: 'ci-argo-compute', description: 'Helm Deployment Name')
    }
    environment {
        PROJECT_NAME = "polusai/compute"
    }
    triggers {
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('Deploy to CI with Helm') {
            steps {
                // Helm values are stored in yaml file in Jenkins
                configFileProvider([configFile(fileId: 'ci-argo-helm-values', targetLocation: 'ci-values.yaml')]) {               
                    withAWS(credentials:'aws-jenkins-eks') {
                        sh "aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME}"
                        sh "helm upgrade --install ${HELM_DEPLOYMENT_NAME} deploy/helm/argo-driver --values ci-values.yaml --namespace ${KUBERNETES_NAMESPACE}"
                    }
                }
            }
        }
    }
}