apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongo-pv
spec:
    storageClassName: hostpath
    capacity:
        storage: 256Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: REPLACE_ME_WITH_PATH_TO_DATA
