pipeline {
    agent {
        docker { 
            image 'sunnielyu/helm-jenkins:0.4.0'
            label 'linux && build && aws'
        }
    }
    options { timestamps () }
    parameters {
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'kube-eks-ci-compute', description: 'Kubernetes Cluster to deploy')
        string(name: 'KUBERNETES_NAMESPACE', defaultValue: 'default', description: 'Cluster Namespace to deploy')
        string(name: 'HELM_DEPLOYMENT_NAME', defaultValue: 'ci-compute', description: 'Helm Deployment Name')
    }
    environment {
        PROJECT_NAME = "polusai/compute"
        XDG_CONFIG_HOME = "/root/config"
    }
    triggers {
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('Deploy to CI with Helm') {
            steps {
                dir('deploy/helm/api') {
                    // Helm values are stored in yaml file in Jenkins
                    configFileProvider([configFile(fileId: 'ci-helm-values', targetLocation: 'ci-values.yaml')]) {               
                        withAWS(credentials:'aws-jenkins-eks') {
                            sh "aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME}"
                            sh "mkdir /config/helm"
                            sh "helm repo add bitnami https://charts.bitnami.com/bitnami"
                            sh "helm dependency update"
                            sh "helm dependency build"
                            sh "helm upgrade --install ${HELM_DEPLOYMENT_NAME} . --values ci-values.yaml --namespace ${KUBERNETES_NAMESPACE}" 
                        }
                    }
                }
            }
        }
    }
}