apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
spec:
  type: NodePort
  ports:
    - port: {{.Values.argo.port}}
      targetPort: {{.Values.argo.port}}
  selector:
    app: {{.Release.Name}}
