compute:
  name: compute
  image: 
    name: polusai/compute:0.0.1
    secret: notebooks-hub-polusai-secret
  ingress:
    enabled: false
    host: COMPUTE_INGRESS_REPLACE
  argo:
    name: compute-argo
  slurm:
    host: HPC_LOGON_NODE_REPLACE
  mongo:
    name: compute-mongodb
  auth:
    url: SERVICES_AUTH_URL
    tenant: SERVICES_AUTH_TENANT

mongodb:
  persistence:
    enabled: false
    size: 256Mi
    storageClass: local
  auth:
    ## @param auth.enabled Enable authentication
    ## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
    ##
    enabled: false
