kind: PersistentVolume
apiVersion: v1
metadata:
  name: compute-data-volume
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/path/to/compute/data"