{{- if .Values.driver.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: '{{ .Release.Name }}'
spec:
  rules:
    - host: {{.Values.driver.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}
                port:
                  number: {{.Values.driver.port}}
{{- end }}