apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Release.Name}}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - delete
      - deletecollection
      - get
      - list
      - patch
      - create
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Release.Name}}
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}
roleRef:
  kind: Role
  name: {{.Release.Name}}
  apiGroup: rbac.authorization.k8s.io
