name: Build Compute API Docker images

on:
    push:
        branches:
            - main

jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main
              with:
                  path: packages/api

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build Docker image
              uses: docker/build-push-action@v2
              with:
                  context: packages/api
                  push: true
                  tags: polusai/compute-api:${{ steps.package-version.outputs.current-version}}
                  build-args: |
                      NPM_TOKEN=${{secrets.NPM_TOKEN}}
