name: Build Argo Compute driver Docker images

on:
    push:
        branches:
            - docker
    pull_request:
        branches:
            - main
        types:
            - closed
    workflow_dispatch:

jobs:
    docker-build-argo:
        # if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Check Paths
              id: changes
              uses: dorny/paths-filter@v2
              with:
                filters: |
                    api:
                        - 'packages/argo-driver/**'
                
             - name: Set CalVer and PR ID
              run: |
                echo "ARGO_VERSION=$(date +%Y.%m.%d)-${{ github.event.pull_request.number || '0' }}" >> $GITHUB_ENV

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build Docker image
              uses: docker/build-push-action@v2
            #   if: steps.changes.outputs.api == 'true'
              with:
                  context: .
                  file: ./Dockerfile.argo
                  push: true
                  tags: polusai/argo-driver:${{ env.ARGO_VERSION }}
