name: Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
  
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release PR
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.POLUS_COMPUTE_GITHUB }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish Compute API Docker image
        if: ${{ steps.release.outputs['packages/api--release_created'] == 'true'}} 
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: polusai/compute-api:${{ steps.release.outputs['packages/api--tag_name'] }}

      - name: Publish Argo Driver Docker image
        if: ${{ steps.release.outputs['packages/argo-driver--release_created'] == 'true'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.argo
          push: true
          tags: polusai/compute-argo-driver:${{ steps.release.outputs['packages/argo-driver--tag_name'] }}

      - name: Publish Single Node Driver Docker image
        if: ${{ steps.release.outputs['packages/single-node-driver--release_created'] == 'true'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.sn
          push: true
          tags: polusai/compute-single-node-driver:${{ steps.release.outputs['packages/single-node-driver--tag_name'] }}

      - name: Publish Slurm Driver Docker image
        if: ${{ steps.release.outputs['packages/slurm-driver--release_created'] == 'true'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.slurm
          push: true
          tags: polusai/compute-slurm-driver:${{ steps.release.outputs['packages/slurm-driver--tag_name'] }}
